name: the_memory_match_game
description: A new Flutter project.

version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
